# Generated by Django 3.0.6 on 2020-06-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='sendgrid_id',
            new_name='mailjet_id',
        ),
    ]
