# Generated by Django 3.0.6 on 2020-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_auto_20200611_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='mailjet_draft_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
