# Generated by Django 3.0.6 on 2020-06-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_emailcampaign_mailjet_draft_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='mailjet_draft_id',
        ),
    ]
