# Generated by Django 3.0.6 on 2020-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0004_remove_emailcampaign_mailjet_draft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
