# Generated by Django 3.0.6 on 2020-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0005_emailcampaign_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='template',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='isScheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='send_at',
            field=models.DateTimeField(null=True),
        ),
    ]
