# Generated by Django 3.0.6 on 2020-06-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0006_auto_20200612_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='mailjet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
