# Generated by Django 3.0.6 on 2020-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0007_auto_20200612_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='send_at',
            field=models.DateField(null=True),
        ),
    ]
