# Generated by Django 3.0.6 on 2020-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0008_auto_20200612_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='send_at',
            field=models.DateTimeField(null=True),
        ),
    ]
