# Generated by Django 3.0.6 on 2020-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0011_auto_20200612_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='mailjet_custom_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
