# Generated by Django 3.0.6 on 2020-06-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medias', '0005_emailmedia'),
        ('Email', '0012_emailcampaign_mailjet_custom_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='media',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_campaigns', to='Medias.EmailMedia'),
        ),
    ]
