# Generated by Django 3.0.6 on 2020-06-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0005_auto_20200609_2042'),
        ('Vendor', '0003_auto_20200608_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('send_at', models.DateTimeField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField()),
                ('to', models.ManyToManyField(related_name='sms_campaigns', to='Customer.Customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to='Vendor.Vendor')),
            ],
        ),
    ]
