# Generated by Django 3.0.6 on 2020-06-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_auto_20200609_1054'),
        ('Customer', '0003_customer_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Discount.AmountDiscount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_discounted',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='percent_discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Discount.PercentDiscount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='point_discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Discount.PointsDiscount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
