# Generated by Django 3.0.6 on 2020-06-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0003_auto_20200608_1620'),
        ('Medias', '0003_auto_20200608_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=40)),
                ('min_points', models.IntegerField()),
                ('type_amount', models.CharField(choices=[('M', 'Euros'), ('P', 'Pourcentage')], max_length=1)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_discounts', to='Medias.DiscountMedia')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_discounts', to='Vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PercentDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percent_discounts', to='Medias.DiscountMedia')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent_discounts', to='Vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='AmountDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=40)),
                ('min_bill', models.IntegerField()),
                ('type_amount', models.CharField(choices=[('M', 'Euros'), ('P', 'Pourcentage')], max_length=1)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_discounts', to='Medias.DiscountMedia')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_discounts', to='Vendor.Vendor')),
            ],
        ),
    ]
