# Generated by Django 3.0.6 on 2020-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vendors/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
