# Generated by Django 3.0.6 on 2020-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medias', '0002_articlemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='discounts/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='file',
            field=models.FileField(upload_to='articles/'),
        ),
    ]
