# Generated by Django 3.0.6 on 2020-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medias', '0003_auto_20200608_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trainings/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
