# Generated by Django 3.0.6 on 2020-06-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medias', '0006_socialmedia'),
        ('Vendor', '0003_auto_20200608_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('send_at', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_posts', to='Medias.SocialMedia')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_posts', to='Vendor.Vendor')),
            ],
        ),
    ]
